version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-svc
    ports:
      - "27017:27017"
    environment:
      MONGO_DB: mydatabase
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-svc
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Redis default port
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo-event-store:
    image: mongo
    container_name: mongo-event-store-svc
    ports:
      - "27018:27017"
    environment:
      MONGO_DB: event-stored
    command: mongod --replSet event-store-repl-set
    volumes:
      - ./notification-svc/scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  notification-svc:
    build:
      context: ./notification-svc
      dockerfile: Dockerfile
    image: notification-svc
    container_name: notification-svc
    ports:
      - "3000:3000"
    volumes:
      - ./notification-svc:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo
    stdin_open: true
    tty: true

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
