filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nestjs/*.log
    fields:
      service: nestjs
    multiline.pattern: '^{'
    multiline.negate: true
    multiline.match: after

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]

setup.template.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
