version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ management console
      - "5672:5672" # RabbitMQ communication port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  nestjs-service:
    build: ./nestjs
    container_name: nestjs-service
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - default

  golang-service:
    build: ./go
    container_name: golang-service
    depends_on:
      - rabbitmq
    ports:
      - "4000:4000"
    networks:
      - default

networks:
  default:
    name: my-network
